# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-22 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buzz',
            name='title',
        ),
    ]
