# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buzzer', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('lang', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
