# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-19 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buzzer', '0003_buser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buser',
        ),
    ]
